### ISSUE TITLE
Grafana dashboards

### ISSUE THREAD

**Issue by andygout** [Financial-Times/next-api#19]
[Grafana dashboards](http://grafana.ft.com/dashboard/db/next-api)
## To Do:
- Merge EU + US where possible.
- Fetch Counts: 'By Concept' not getting any counts... (does this need to be included at all?).
- Most Fetches, Slowest Fetches (Median), Peak Most Fetches, Peak Slowest Fetches (median), Most Errored Fetches: all require `sortByTotal()` function to be applied (once fixed by Willem).
## To Add:
- Ratio of errors count vs. all fetches count.
- Ratio of cache hits vs misses.
- Average response 2xx time.
- Metrics for requests that make multiple queries (Patrick Hamann).
- Metrics to make comparisons against existing GraphQL-API (can it fetch quicker?, etc.).

**Comment by ironsidevsquincy** [comment]
Think this is done
