### ISSUE TITLE
Consider less decoration within graphQL

### ISSUE THREAD

**Issue by leggsimon** [Financial-Times/next-api#48]
Within [this video resolve](https://github.com/Financial-Times/next-api/blob/master/server/graphql/types/media/video.js#L79) we are decorating a time in milliseconds to a string of `"minutes:seconds"`
eg. `323000` => `"5:23"`
Rather than doing this here, should we just expose the data in milliseconds and do the transform to that format wherever it is consumed?

**Comment by ironsidevsquincy** [comment]
We now have https://github.com/Financial-Times/next-api/blob/master/server/graphql/types/content.js#L715
